# Generated by Django 5.2.5 on 2025-10-28 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('position', models.CharField(choices=[('developer', 'Developer'), ('designer', 'UI/UX Designer'), ('mobile_developer', 'Mobile Developer'), ('server_admin', 'Server Administrator'), ('tester', 'Tester'), ('manager', 'Project Manager'), ('intern', 'Intern')], max_length=50)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Optional profile picture', null=True, upload_to='members/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='If this member is linked to a user account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SET Member',
                'verbose_name_plural': 'SET Members',
                'ordering': ['-created_at'],
            },
        ),
    ]
