# Generated by Django 5.2.5 on 2025-10-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, choices=[('SET', 'Software Engineering Team'), ('HET', 'Hardware Engineering Team'), ('TRAINING', 'Training & Learning')], editable=False, max_length=30, null=True),
        ),
    ]
