# Generated by Django 5.2.5 on 2025-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0003_member_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('lance_corporal', 'Lance Corporal'), ('coporal', 'Coporal'), ('sergeant', 'Sergeant'), ('warrant_officer_class-1', 'Warrant Officer Class - I'), ('warrant_officer_class-2', 'Warrant Officer Class - II'), ('second Lieutenant', 'Second Lieutenant'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('colonel', 'Colonel'), ('general', 'General')], max_length=50, null=True),
        ),
    ]
