# Generated by Django 5.2.5 on 2025-10-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Select members working on this project', related_name='member_projects', to='set.member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='set.member'),
        ),
    ]
