# Generated by Django 5.2.5 on 2025-10-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0007_alter_project_members_alter_project_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
