# Generated by Django 5.2.5 on 2025-10-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0008_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
