# Generated by Django 5.2.5 on 2025-10-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0009_remove_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_document',
            field=models.FileField(blank=True, help_text='Optional project document', null=True, upload_to='set/projects/docs/'),
        ),
    ]
