# Generated by Django 5.2.5 on 2025-10-29 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0010_project_project_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
