# Generated by Django 5.2.5 on 2025-10-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0014_task_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
