# Generated by Django 5.2.5 on 2025-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0015_remove_task_progress_project_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwarerequirement',
            name='status',
        ),
        migrations.AlterField(
            model_name='softwarerequirement',
            name='department',
            field=models.CharField(choices=[('office', 'Office'), ('set', 'Software Engineering Team'), ('het', 'Hardware Engineering Team'), ('training', 'Training School')], max_length=20),
        ),
    ]
