# Generated by Django 5.2.5 on 2025-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0016_remove_softwarerequirement_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ကျား'), ('female', 'မ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'တပ်သား'), ('lance_corporal', 'ဒုတပ်ကြပ်'), ('coporal', 'တပ်ကြပ်'), ('sergeant', 'တပ်ကြပ်ကြီး'), ('warrant_officer_class-2', 'ဒု-အရာခံဗိုလ်'), ('warrant_officer_class-1', 'အရာခံဗိုလ်'), ('second Lieutenant', 'ဒုဗိုလ်'), ('lieutenant', 'ဗိုလ်'), ('captain', 'ဗိုလ်ကြီး'), ('major', 'ဗိုလ်မှူး'), ('colonel', 'ဗိုလ်မှူးကြီး'), ('general', 'ဗိုလ်ချုပ်')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='softwarerequirement',
            name='month',
            field=models.CharField(choices=[('01', 'ဇန်နဝါရီလ'), ('02', 'ဖေဖော်ဝါရီလရီလ'), ('03', 'မတ်ချ်လ'), ('04', 'ဧပြီလ'), ('05', 'မေလ'), ('06', 'ဂျုန်လလ'), ('07', 'ဂျူလိုင်လ'), ('08', 'သြဂတ်စ်လ'), ('09', 'စပ်တမ်ဘာလ'), ('10', 'အောက်တိုဘာလ'), ('11', 'နိုဗမ်ဘာလ'), ('12', 'ဒီဇင်ဘာလ')], max_length=2),
        ),
    ]
