# Generated by Django 5.2.8 on 2025-11-20 01:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0018_softwarespendingmoney_delete_softwarerequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('commit', 'Commit'), ('issue', 'Issue'), ('project', 'Project Update'), ('developer', 'Developer Update')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
