# Generated by Django 5.2.8 on 2025-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0020_remove_project_progress_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'နိမ့်'), ('MEDIUM', 'အလယ်အလတ်'), ('HIGH', 'မြင့်')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'အစီအစိုင်ဆွဲနိန်'), ('ONGOING', 'လုပ်နိန်ဆဲ'), ('COMPLETED', 'ပြီးစီး'), ('ONHOLD', 'ရပ်တန့်'), ('CANCELLED', 'ပယ်ဖျက်')], default='PLANNING', max_length=20),
        ),
    ]
