# Generated by Django 5.2.8 on 2025-12-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0022_alter_member_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Optional profile picture', null=True, upload_to='members/photos/'),
        ),
    ]
