# Generated by Django 5.2.8 on 2025-12-16 02:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0023_alter_member_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional profile picture', max_length=255, null=True, verbose_name='members/photos/'),
        ),
    ]
