# Generated by Django 5.2.5 on 2025-10-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('set', 'Software Engineering Team'), ('het', 'Hardware Engineering Team'), ('training', 'Training & Learning')], default='\u200cadmin', max_length=20),
        ),
    ]
