# Generated by Django 5.2.8 on 2025-12-03 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text='e.g. Kyaw Soe Hla Laptop', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('is_allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
