# Generated by Django 5.2.5 on 2025-10-29 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, choices=[('SET', 'Software Engineering Team'), ('HET', 'Hardware Engineering Team'), ('TRAINING', 'Training & Learning')], editable=False, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, choices=[('private', 'Private'), ('lance_corporal', 'Lance Corporal'), ('coporal', 'Coporal'), ('sergeant', 'Sergeant'), ('warrant_officer_class-1', 'Warrant Officer Class - I'), ('warrant_officer_class-2', 'Warrant Officer Class - II'), ('second Lieutenant', 'Second Lieutenant'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('colonel', 'Colonel'), ('general', 'General')], max_length=50, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('position', models.CharField(choices=[('developer', 'Developer'), ('designer', 'UI/UX Designer'), ('mobile_developer', 'Mobile Developer'), ('server_admin', 'Server Administrator'), ('tester', 'Tester'), ('manager', 'Project Manager'), ('intern', 'Intern')], max_length=50)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Optional profile picture', null=True, upload_to='members/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='If this member is linked to a user account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='het_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HET Member',
                'verbose_name_plural': 'HET Members',
                'ordering': ['-created_at'],
            },
        ),
    ]
