# Generated by Django 5.2.5 on 2025-10-30 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('computer', 'Computer / Laptop'), ('mobile', 'Mobile Device'), ('printer', 'Printer'), ('network', 'Network Equipment'), ('sensor', 'Sensor'), ('controller', 'Controller Board'), ('other', 'Other')], default='other', max_length=50)),
                ('issue_description', models.TextField(help_text='Describe the problem in detail')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='het/devices/before/')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='het/devices/after/')),
                ('report_document', models.FileField(blank=True, null=True, upload_to='het/devices/reports/')),
                ('repair_notes', models.TextField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repairs', to=settings.AUTH_USER_MODEL)),
                ('support_team', models.ManyToManyField(blank=True, related_name='repair_tasks', to='het.member')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repairs', to='het.member')),
            ],
            options={
                'verbose_name': 'Hardware Repair',
                'verbose_name_plural': 'Hardware Repairs',
                'ordering': ['-created_at'],
            },
        ),
    ]
