# Generated by Django 5.2.5 on 2025-10-30 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0002_hardwarerepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarerepair',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
