# Generated by Django 5.2.5 on 2025-10-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0003_alter_hardwarerepair_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarerepair',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
