# Generated by Django 5.2.5 on 2025-10-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0006_hardwaremonthlyrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaremonthlyrequirement',
            name='month',
            field=models.IntegerField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')]),
        ),
        migrations.AlterField(
            model_name='hardwaremonthlyrequirement',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
