# Generated by Django 5.2.5 on 2025-10-31 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0008_hardwarerequirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarerequirement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='het_approved_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hardwarerequirement',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='het_requested_requirements', to=settings.AUTH_USER_MODEL),
        ),
    ]
