# Generated by Django 5.2.5 on 2025-11-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0009_alter_hardwarerequirement_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarerepair',
            name='priority',
            field=models.CharField(choices=[('low', 'နိမ့်'), ('medium', 'အတန်အသင့်'), ('high', 'အရေးကြီး'), ('urgent', 'လုံးဝအရေးကြီး')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='hardwarerepair',
            name='status',
            field=models.CharField(choices=[('pending', 'စောင့်ဆိုင်းဆဲ'), ('in_progress', 'ပြုပြင်ဆဲ'), ('completed', 'ပြီးစီး'), ('cancelled', 'ပယ်ဖျက်ပယ်ဖျက်')], default='pending', max_length=20),
        ),
    ]
