# Generated by Django 5.2.5 on 2025-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0010_alter_hardwarerepair_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwarerequirement',
            name='status',
        ),
        migrations.AlterField(
            model_name='hardwarerequirement',
            name='department',
            field=models.CharField(choices=[('office', 'Office'), ('set', 'Software Engineering Team'), ('het', 'Hardware Engineering Team'), ('training', 'Training School')], max_length=20),
        ),
    ]
