# Generated by Django 5.2.5 on 2025-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0011_remove_hardwarerequirement_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarerequirement',
            name='month',
            field=models.CharField(choices=[('01', 'ဇန်နဝါရီလ'), ('02', 'ဖေဖော်ဝါရီလရီလ'), ('03', 'မတ်ချ်လ'), ('04', 'ဧပြီလ'), ('05', 'မေလ'), ('06', 'ဂျုန်လလ'), ('07', 'ဂျူလိုင်လ'), ('08', 'သြဂတ်စ်လ'), ('09', 'စပ်တမ်ဘာလ'), ('10', 'အောက်တိုဘာလ'), ('11', 'နိုဗမ်ဘာလ'), ('12', 'ဒီဇင်ဘာလ')], max_length=2),
        ),
    ]
