# Generated by Django 5.2.8 on 2025-11-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0013_hardwarespendingmoney_delete_hardwarerequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ကျား'), ('female', 'မ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('phone', 'ဖုန်းပြုပြင်သူ'), ('computer', 'ကွန်ပျူတာပြုပြင်သူ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'တပ်သား'), ('lance_corporal', 'ဒု-တပ်ကြပ်'), ('coporal', 'တပ်ကြပ်'), ('sergeant', 'တပ်ကြပ်ကြီး'), ('warrant_officer_class-2', 'ဒုအရာခံဗိုလ်'), ('warrant_officer_class-1', 'အရာခံဗိုလ်'), ('second Lieutenant', 'ဒုဗိုလ်'), ('lieutenant', 'ဗိုလ်'), ('captain', 'ဗိုလ်ကြီး'), ('major', 'ဗိုလ်မှူး'), ('colonel', 'ဗိုလ်မှူးကြီး'), ('general', 'ဗိုလ်ချုပ်')], max_length=50, null=True),
        ),
    ]
