# Generated by Django 5.2.8 on 2025-11-26 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0014_alter_member_gender_alter_member_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('install', 'Installation'), ('network', 'Network Fix'), ('power', 'Electrical Work'), ('other', 'Other')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
