# Generated by Django 5.2.8 on 2025-12-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('het', '0015_hardwareactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareactivity',
            name='type',
            field=models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('install', 'Installation'), ('network', 'Network Fix'), ('power', 'Electrical Work'), ('other', 'Other'), ('issue', 'Issue'), ('sensor', 'Sensor'), ('controller', 'Controller Board'), ('member', 'Member')], max_length=20),
        ),
    ]
