# Generated by Django 5.2.5 on 2025-10-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('theme', models.CharField(default='light', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('system_warnings', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=False)),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
