# Generated by Django 5.2.5 on 2025-10-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Engineering Management Dashboard', max_length=100)),
                ('organization', models.CharField(default='Software Engineering Team II', max_length=100)),
                ('theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('system_warnings', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=False)),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
