# Generated by Django 5.2.5 on 2025-10-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_systemsettings_delete_systemsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='theme',
        ),
    ]
