# Generated by Django 5.2.5 on 2025-10-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_systemsettings_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='min_password_length',
        ),
    ]
