# Generated by Django 5.2.5 on 2025-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_spendingmoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spendingmoney',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='spendingmoney',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='spendingmoney',
            name='status',
        ),
        migrations.AlterField(
            model_name='spendingmoney',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='spending_money/docs/'),
        ),
        migrations.AlterField(
            model_name='spendingmoney',
            name='department',
            field=models.CharField(choices=[('office', 'Office'), ('set', 'Software Engineering Team'), ('het', 'Hardware Engineering Team'), ('training', 'Training School')], max_length=20),
        ),
    ]
