# Generated by Django 5.2.5 on 2025-11-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at'], 'verbose_name': 'Training Member', 'verbose_name_plural': 'Training Members'},
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('designer', 'UI/UX Designer'), ('mobile_developer', 'Mobile Developer'), ('server_admin', 'Server Administrator'), ('tester', 'Tester'), ('manager', 'Project Manager'), ('intern', 'Intern')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='reg_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
