# Generated by Django 5.2.5 on 2025-11-15 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_member_options_alter_member_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSpendingMoney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('office', 'Office'), ('set', 'Software Engineering Team'), ('het', 'Hardware Engineering Team'), ('training', 'Training School')], max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(choices=[('01', 'ဇန်နဝါရီလ'), ('02', 'ဖေဖော်ဝါရီလရီလ'), ('03', 'မတ်ချ်လ'), ('04', 'ဧပြီလ'), ('05', 'မေလ'), ('06', 'ဂျုန်လလ'), ('07', 'ဂျူလိုင်လ'), ('08', 'သြဂတ်စ်လ'), ('09', 'စပ်တမ်ဘာလ'), ('10', 'အောက်တိုဘာလ'), ('11', 'နိုဗမ်ဘာလ'), ('12', 'ဒီဇင်ဘာလ')], max_length=2)),
                ('year', models.IntegerField(default=2025)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(default='pcs', help_text='e.g. pcs, box, meter, etc.', max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='training/requirements/docs/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_approved_spending_money', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requested_spending_money', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TrainingRequirement',
        ),
    ]
