# Generated by Django 5.2.8 on 2025-12-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_trainingspendingmoney_delete_trainingrequirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingspendingmoney',
            options={'ordering': ['year', 'month'], 'verbose_name': 'Training Spending Money', 'verbose_name_plural': 'Training Spending Money'},
        ),
    ]
